name: CI Deploy

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: cargo build --profile release-prod

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ergtools
          path: target/release-prod/ergtools

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ergtools
          path: .

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Upload binary
        run: |
          scp ergtools ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/ergtools/ergtools.new

      - name: Restart services
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            chmod +x ~/ergtools/ergtools.new
            sudo systemctl stop ergtools
            mv ~/ergtools/ergtools.new ~/ergtools/ergtools
            sudo systemctl start ergtools
          EOF
